spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false


  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: true
  mvc: 
    throw-exception-if-no-handler-found: true
  web: 
    resources:
      add-mappings: false
    

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO

management:
  endpoint:
    health:
      show-details: when_authorized
      
server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT:8080}

