spring:
  application:
    name: hisaablite
  config:
    import: optional:application-secrets.yml

  profiles:
    active: dev
  
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  mvc:
    favicon:
      enabled: true
